services:
  - type: web
    name: linkvault-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SKIP_FIREBASE
        value: true
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0